version: '3.7'

volumes:
  opennebula_certs:
  opennebula_db:
  opennebula_data:
  opennebula_sharedtmp:
  oneadmin_auth_data:
  oneadmin_ssh_priv_data:
  oneadmin_ssh_pub_data:

networks:
  onenet:
#    external: true

services:
  opennebula-mysql:
    env_file:
      - ".env"
    #image: mariadb:10
    image: "${OPENNEBULA_FRONTEND_IMAGE_NAME:-opennebula-frontend}:${OPENNEBULA_FRONTEND_IMAGE_TAG:-latest}"
    restart: always
    environment:
      OPENNEBULA_FRONTEND_SERVICE: "mysqld"
    volumes:
      - opennebula_db:/var/lib/mysql
    networks:
      - onenet
    healthcheck:
      test: ["CMD", "/onedocker-healthcheck.sh"]
      interval: "10s"
      timeout: "10s"
      retries: 3
      start_period: "2m"
    deploy:
      restart_policy:
        condition: any
        delay: 10s
      replicas: 1

  opennebula-frontend:
    env_file:
      - ".env"
    image: "${OPENNEBULA_FRONTEND_IMAGE_NAME:-opennebula-frontend}:${OPENNEBULA_FRONTEND_IMAGE_TAG:-latest}"
    init: true
    #privileged: true
    restart: always
    environment:
      OPENNEBULA_FRONTEND_SERVICE: "oned"
      ONEADMIN_SSH_PRIVKEY: "/ssh/id_rsa"
      ONEADMIN_SSH_PUBKEY: "/ssh/id_rsa.pub"
    depends_on:
      - opennebula-mysql
    ports:
      - "${OPENNEBULA_FRONTEND_PUBLISH_ADDR:-0.0.0.0}:${OPENNEBULA_ONED_PUBLISHED_APIPORT:-2633}:${OPENNEBULA_ONED_TLSPROXY_APIPORT:-2633}"
    volumes:
      - opennebula_certs:/cert_data
      - opennebula_data:/data
      - opennebula_sharedtmp:/var/tmp/sunstone
      - oneadmin_auth_data:/oneadmin/auth_data
      - oneadmin_ssh_priv_data:/oneadmin/ssh_data
      - oneadmin_ssh_pub_data:/oneadmin/ssh_pub_data
      - ./certs:/certs:ro
      - ./ssh:/ssh:ro
      # enable docker.sock if you want the DockerHub marketplace to work...
      #- /var/run/docker.sock:/var/run/docker.sock
    tmpfs:
      - /run
      - /run/lock
      - /tmp
      - /var/tmp
      - /var/lib/containers
      - /var/lib/docker
    networks:
      - onenet
    healthcheck:
      test: ["CMD", "/onedocker-healthcheck.sh"]
      interval: "10s"
      timeout: "10s"
      retries: 3
      start_period: "2m"
    deploy:
      restart_policy:
        condition: any
        delay: 10s
      replicas: 1

  opennebula-frontend-ssh:
    env_file:
      - ".env"
    image: "${OPENNEBULA_FRONTEND_IMAGE_NAME:-opennebula-frontend}:${OPENNEBULA_FRONTEND_IMAGE_TAG:-latest}"
    init: true
    restart: always
    environment:
      OPENNEBULA_FRONTEND_SERVICE: "sshd"
    ports:
      - "${OPENNEBULA_FRONTEND_PUBLISH_ADDR:-0.0.0.0}:${OPENNEBULA_FRONTEND_PUBLISHED_SSHPORT:-2222}:22"
    depends_on:
      - opennebula-frontend
    volumes:
      - opennebula_data:/data
      - oneadmin_ssh_pub_data:/oneadmin/ssh_pub_data
    tmpfs:
      - /run
      - /run/lock
      - /tmp
      - /var/tmp
    networks:
      - onenet
    healthcheck:
      test: ["CMD", "/onedocker-healthcheck.sh"]
      interval: "10s"
      timeout: "10s"
      retries: 3
      start_period: "2m"
    deploy:
      restart_policy:
        condition: any
        delay: 10s
      replicas: 1

  opennebula-memcached:
    env_file:
      - ".env"
    image: "${OPENNEBULA_FRONTEND_IMAGE_NAME:-opennebula-frontend}:${OPENNEBULA_FRONTEND_IMAGE_TAG:-latest}"
    init: true
    restart: always
    environment:
      OPENNEBULA_FRONTEND_SERVICE: "memcached"
    tmpfs:
      - /run
      - /run/lock
      - /tmp
      - /var/tmp
    networks:
      - onenet
    healthcheck:
      test: ["CMD", "/onedocker-healthcheck.sh"]
      interval: "10s"
      timeout: "10s"
      retries: 3
      start_period: "2m"
    deploy:
      restart_policy:
        condition: any
        delay: 10s
      replicas: 1

  opennebula-scheduler:
    env_file:
      - ".env"
    image: "${OPENNEBULA_FRONTEND_IMAGE_NAME:-opennebula-frontend}:${OPENNEBULA_FRONTEND_IMAGE_TAG:-latest}"
    init: true
    restart: always
    environment:
      OPENNEBULA_FRONTEND_SERVICE: "scheduler"
    depends_on:
      - opennebula-frontend
    volumes:
      - oneadmin_auth_data:/oneadmin/auth_data
    tmpfs:
      - /run
      - /run/lock
      - /tmp
      - /var/tmp
    networks:
      - onenet
    healthcheck:
      test: ["CMD", "/onedocker-healthcheck.sh"]
      interval: "10s"
      timeout: "10s"
      retries: 3
      start_period: "2m"
    deploy:
      restart_policy:
        condition: any
        delay: 10s
      replicas: 1

  opennebula-flow:
    env_file:
      - ".env"
    image: "${OPENNEBULA_FRONTEND_IMAGE_NAME:-opennebula-frontend}:${OPENNEBULA_FRONTEND_IMAGE_TAG:-latest}"
    init: true
    restart: always
    environment:
      OPENNEBULA_FRONTEND_SERVICE: "oneflow"
    depends_on:
      - opennebula-frontend
    ports:
      - "${OPENNEBULA_FRONTEND_PUBLISH_ADDR:-0.0.0.0}:${OPENNEBULA_ONEFLOW_PUBLISHED_APIPORT:-2474}:${OPENNEBULA_ONEFLOW_TLSPROXY_APIPORT:-2474}"
    volumes:
      - oneadmin_auth_data:/oneadmin/auth_data
      - opennebula_certs:/cert_data:ro
    tmpfs:
      - /run
      - /run/lock
      - /tmp
      - /var/tmp
    networks:
      - onenet
    healthcheck:
      test: ["CMD", "/onedocker-healthcheck.sh"]
      interval: "10s"
      timeout: "10s"
      retries: 3
      start_period: "2m"
    deploy:
      restart_policy:
        condition: any
        delay: 10s
      replicas: 1

  opennebula-gate:
    env_file:
      - ".env"
    image: "${OPENNEBULA_FRONTEND_IMAGE_NAME:-opennebula-frontend}:${OPENNEBULA_FRONTEND_IMAGE_TAG:-latest}"
    init: true
    restart: always
    environment:
      OPENNEBULA_FRONTEND_SERVICE: "onegate"
    depends_on:
      - opennebula-frontend
    ports:
      - "${OPENNEBULA_FRONTEND_PUBLISH_ADDR:-0.0.0.0}:${OPENNEBULA_ONEGATE_PUBLISHED_APIPORT:-5030}:${OPENNEBULA_ONEGATE_TLSPROXY_APIPORT:-5030}"
    volumes:
      - oneadmin_auth_data:/oneadmin/auth_data
      - opennebula_certs:/cert_data:ro
    tmpfs:
      - /run
      - /run/lock
      - /tmp
      - /var/tmp
    networks:
      - onenet
    healthcheck:
      test: ["CMD", "/onedocker-healthcheck.sh"]
      interval: "10s"
      timeout: "10s"
      retries: 3
      start_period: "2m"
    deploy:
      restart_policy:
        condition: any
        delay: 10s
      replicas: 1

  opennebula-sunstone:
    env_file:
      - ".env"
    image: "${OPENNEBULA_FRONTEND_IMAGE_NAME:-opennebula-frontend}:${OPENNEBULA_FRONTEND_IMAGE_TAG:-latest}"
    init: true
    restart: always
    environment:
      OPENNEBULA_FRONTEND_SERVICE: "sunstone"
    depends_on:
      - opennebula-frontend
    ports:
      - "${OPENNEBULA_FRONTEND_PUBLISH_ADDR:-0.0.0.0}:${OPENNEBULA_SUNSTONE_PUBLISHED_HTTPPORT:-9869}:${OPENNEBULA_SUNSTONE_HTTPPORT:-9869}"
      - "${OPENNEBULA_FRONTEND_PUBLISH_ADDR:-0.0.0.0}:${OPENNEBULA_SUNSTONE_PUBLISHED_HTTPSPORT:-4443}:${OPENNEBULA_SUNSTONE_HTTPSPORT:-443}"
      - "${OPENNEBULA_FRONTEND_PUBLISH_ADDR:-0.0.0.0}:${OPENNEBULA_SUNSTONE_PUBLISHED_VNCPORT:-29876}:29876"
    volumes:
      - opennebula_certs:/cert_data
      - opennebula_sharedtmp:/var/tmp/sunstone
      - oneadmin_auth_data:/oneadmin/auth_data
      - ./certs:/certs:ro
    tmpfs:
      - /run
      - /run/lock
      - /tmp
      - /var/tmp
    networks:
      - onenet
    healthcheck:
      test: ["CMD", "/onedocker-healthcheck.sh"]
      interval: "10s"
      timeout: "10s"
      retries: 3
      start_period: "2m"
    deploy:
      restart_policy:
        condition: any
        delay: 10s
      replicas: 1

# TODO: return to this when fireedge is finished
#  opennebula-fireedge:
#    env_file:
#      - ".env"
#    image: "${OPENNEBULA_FRONTEND_IMAGE_NAME:-opennebula-frontend}:${OPENNEBULA_FRONTEND_IMAGE_TAG:-latest}"
#    init: true
#    restart: always
#    environment:
#      OPENNEBULA_FRONTEND_SERVICE: "fireedge"
#    depends_on:
#      - opennebula-frontend
#    ports:
#      - "${OPENNEBULA_FRONTEND_PUBLISH_ADDR:-0.0.0.0}:${OPENNEBULA_FIREEDGE_PUBLISHED_HTTPPORT:-2616}:${OPENNEBULA_SUNSTONE_HTTPPORT:-2616}"
#      - "${OPENNEBULA_FRONTEND_PUBLISH_ADDR:-0.0.0.0}:${OPENNEBULA_FIREEDGE_PUBLISHED_VNCPORT:-4822}:4822"
#    volumes:
#      - oneadmin_auth_data:/oneadmin/auth_data
#    tmpfs:
#      - /run
#      - /run/lock
#      - /tmp
#      - /var/tmp
#    networks:
#      - onenet
#    healthcheck:
#      test: ["CMD", "/onedocker-healthcheck.sh"]
#      interval: "10s"
#      timeout: "10s"
#      retries: 3
#      start_period: "2m"
#    deploy:
#      restart_policy:
#        condition: any
#        delay: 10s
#      replicas: 1

