# ---------------------------------------------------------------------------- #
# Copyright 2020-2021, OpenNebula Project, OpenNebula Systems                  #
#                                                                              #
# Licensed under the Apache License, Version 2.0 (the "License"); you may      #
# not use this file except in compliance with the License. You may obtain      #
# a copy of the License at                                                     #
#                                                                              #
# http://www.apache.org/licenses/LICENSE-2.0                                   #
#                                                                              #
# Unless required by applicable law or agreed to in writing, software          #
# distributed under the License is distributed on an "AS IS" BASIS,            #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.     #
# See the License for the specific language governing permissions and          #
# limitations under the License.                                               #
# ---------------------------------------------------------------------------- #

# This is the referential docker-compose deployment for the official
# OpenNebula front-end container image.

###############################################################################
# PLEASE DO NOT EDIT THIS FILE !                                              #
###############################################################################

version: '3.7'

# common default settings
x-service:
  &default-service
  image: "${DEPLOY_OPENNEBULA_REGISTRY}${DEPLOY_OPENNEBULA_IMAGE_NAME:-opennebula}:${DEPLOY_OPENNEBULA_IMAGE_TAG:-latest}"
  init: true
  env_file:
    - "default.env"
    - "custom.env"
  healthcheck:
    test: ["CMD", "/frontend-healthcheck.sh"]
    interval: "10s"
    timeout: "10s"
    retries: 3
    start_period: "2m"
  tmpfs:
    - /tmp
    - /run
    - /run/lock
  networks:
    - onenet
  restart: always
  stop_grace_period: "90s"

volumes:
  opennebula_mysql:
  opennebula_datastores:
  opennebula_secret_tls:
  opennebula_secret_ssh_host_keys:
  opennebula_oneprovision_ssh:
  opennebula_oneadmin_auth:
  opennebula_oneadmin_ssh:
  opennebula_oneadmin_ssh_copyback:
  opennebula_oneadmin_ssh_provision:
  opennebula_logs:
  opennebula_shared_tmp:
  opennebula_shared_vmrc:

networks:
  onenet:
#    external: true

services:
  opennebula-mysql:
    << : *default-service
    environment:
      OPENNEBULA_FRONTEND_SERVICE: "mysqld"
    volumes:
      - ./config:/config:ro
      - opennebula_mysql:/var/lib/mysql

  opennebula-docker:
    << : *default-service
    privileged: true
    environment:
      OPENNEBULA_FRONTEND_SERVICE: "docker"
    volumes:
      - ./config:/config:ro

  opennebula-oned:
    << : *default-service
    #privileged: true
    cap_add:
      - SYS_ADMIN
    environment:
      OPENNEBULA_FRONTEND_SERVICE: "oned"
    depends_on:
      - opennebula-mysql
    ports:
      - "${DEPLOY_BIND_ADDR:-0.0.0.0}:${DEPLOY_ONED_EXTERNAL_PORT:-2633}:${DEPLOY_ONED_INTERNAL_PORT:-2633}"
    volumes:
      - ./config:/config:ro
      - ./certs:/certs:z
      - ./ssh:/ssh:z
      - opennebula_datastores:/var/lib/one/datastores
      - opennebula_secret_tls:/srv/one/secret-tls
      - opennebula_oneadmin_auth:/var/lib/one/.one
      - opennebula_oneadmin_ssh:/var/lib/one/.ssh
      - opennebula_oneadmin_ssh_copyback:/var/lib/one/.ssh-copyback
      - opennebula_logs:/var/log/one
      - opennebula_shared_tmp:/var/tmp/sunstone
    devices:
      - /dev/fuse:/dev/fuse

  opennebula-sshd:
    << : *default-service
    environment:
      OPENNEBULA_FRONTEND_SERVICE: "sshd"
    ports:
      - "${DEPLOY_BIND_ADDR:-0.0.0.0}:${DEPLOY_SSH_EXTERNAL_PORT:-2222}:22"
    depends_on:
      - opennebula-oned
    volumes:
      - ./config:/config:ro
      - opennebula_datastores:/var/lib/one/datastores
      - opennebula_secret_ssh_host_keys:/srv/one/secret-ssh-host-keys
      - opennebula_oneadmin_ssh_copyback:/var/lib/one/.ssh

  opennebula-memcached:
    << : *default-service
    environment:
      OPENNEBULA_FRONTEND_SERVICE: "memcached"
    volumes:
      - ./config:/config:ro

  opennebula-scheduler:
    << : *default-service
    environment:
      OPENNEBULA_FRONTEND_SERVICE: "scheduler"
    depends_on:
      - opennebula-oned
    volumes:
      - ./config:/config:ro
      - opennebula_oneadmin_auth:/var/lib/one/.one:ro
      - opennebula_logs:/var/log/one

  opennebula-flow:
    << : *default-service
    environment:
      OPENNEBULA_FRONTEND_SERVICE: "oneflow"
    depends_on:
      - opennebula-oned
    ports:
      - "${DEPLOY_BIND_ADDR:-0.0.0.0}:${DEPLOY_ONEFLOW_EXTERNAL_PORT:-2474}:${DEPLOY_ONEFLOW_INTERNAL_PORT:-2474}"
    volumes:
      - ./config:/config:ro
      - opennebula_oneadmin_auth:/var/lib/one/.one:ro
      - opennebula_secret_tls:/srv/one/secret-tls:ro
      - opennebula_logs:/var/log/one

  opennebula-gate:
    << : *default-service
    environment:
      OPENNEBULA_FRONTEND_SERVICE: "onegate"
    depends_on:
      - opennebula-oned
    ports:
      - "${DEPLOY_BIND_ADDR:-0.0.0.0}:${DEPLOY_ONEGATE_EXTERNAL_PORT:-5030}:${DEPLOY_ONEGATE_INTERNAL_PORT:-5030}"
    volumes:
      - ./config:/config:ro
      - opennebula_oneadmin_auth:/var/lib/one/.one:ro
      - opennebula_secret_tls:/srv/one/secret-tls:ro
      - opennebula_logs:/var/log/one

  opennebula-guacd:
    << : *default-service
    environment:
      OPENNEBULA_FRONTEND_SERVICE: "guacd"
    volumes:
      - ./config:/config:ro

  opennebula-sunstone:
    << : *default-service
    environment:
      OPENNEBULA_FRONTEND_SERVICE: "sunstone"
    depends_on:
      - opennebula-oned
    ports:
      - "${DEPLOY_BIND_ADDR:-0.0.0.0}:${DEPLOY_SUNSTONE_EXTERNAL_PORT:-8080}:80"
      - "${DEPLOY_BIND_ADDR:-0.0.0.0}:${DEPLOY_SUNSTONE_EXTERNAL_TLS_PORT:-4443}:443"
      - "${DEPLOY_BIND_ADDR:-0.0.0.0}:${DEPLOY_SUNSTONE_EXTERNAL_VNC_PORT:-29876}:29876"
    volumes:
      - ./config:/config:ro
      - ./certs:/certs:z
      - opennebula_secret_tls:/srv/one/secret-tls
      - opennebula_oneadmin_auth:/var/lib/one/.one:ro
      - opennebula_logs:/var/log/one
      - opennebula_shared_tmp:/var/tmp/sunstone
      - opennebula_shared_vmrc:/var/lib/one/sunstone_vmrc_tokens

  opennebula-fireedge:
    << : *default-service
    environment:
      OPENNEBULA_FRONTEND_SERVICE: "fireedge"
    depends_on:
      - opennebula-oned
    volumes:
      - ./config:/config:ro
      - opennebula_oneadmin_auth:/var/lib/one/.one
      - opennebula_oneadmin_ssh_provision:/var/lib/one/.ssh
      - opennebula_logs:/var/log/one
      - opennebula_shared_vmrc:/var/lib/one/sunstone_vmrc_tokens
    # TODO: remove when fireedge is capable of handling SIGTERM
    stop_grace_period: "10s"

  opennebula-provision:
    << : *default-service
    environment:
      OPENNEBULA_FRONTEND_SERVICE: "oneprovision"
    volumes:
      - ./config:/config:ro
      - opennebula_oneprovision_ssh:/var/lib/one/.ssh-oneprovision
      - opennebula_oneadmin_auth:/var/lib/one/.one
      - opennebula_oneadmin_ssh_provision:/var/lib/one/.ssh
      - opennebula_secret_ssh_host_keys:/srv/one/secret-ssh-host-keys
      - opennebula_logs:/var/log/one
